### ISSUE TITLE
prefer-in-document handle AllBy queries

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-jest-dom#114]
Consider the following code:

Relevant code or config

```javascript
const things = screen.getAllByText("foo");
expect(things).toHaveLength(1);
```

Currently this will get auto-fixed to 

```javascript
const things = screen.getAllByText("foo");
expect(things).toBeInTheDocument();
```
It would be better to change the query to `getByText("foo")` as the current auto-fix will actually break tests.  same applies to query/find

**Comment by benmonro** [comment]
@AntonNiklasson would you mind taking a look at this one? :)

**Comment by G-Rath** [comment]
I could be missing something here, but it seems like you can't use AllBy queries with `toBeInTheDocument`?

My situation is that I'm testing pagination on a table, so I'm moving to the next page and then using `screen.queryAllByText` to find "all" of some test text (that's used for targeting).

It just so happens that in the resulting page, there is only one of these rows which triggers `prefer-in-document` since I'm doing `toHaveLength(1)`.

However, using `toBeInTheDocument` gives me this:

```
Error: expect(received).toBeInTheDocument()

received value must be an HTMLElement or an SVGElement.
Received has type:  array
Received has value: [<td class="MuiTableCell-root MuiTableCell-body MuiTableCell-sizeSmall" role="cell">test-note-1</td>]
```

**Comment by G-Rath** [comment]
Ah, I've found what I'm missing: the fixer changes it to be `queryByText` as well as modifying the `toHaveLength`.

Personally, I'm on the fence about this because as far as I can tell, there isn't any other way to verify that something is only present once, so you can't avoid triggering an eslint rule (either `prefer-to-have-length` or `prefer-in-document`).
