### ISSUE TITLE
Wanna check '.checked' value from the argument using .toBe(true), but i'll get 'jest-dom/prefer-checked'

### ISSUE THREAD

**Issue by ivanEremeev00** [testing-library/eslint-plugin-jest-dom#232]
- `eslint-plugin-jest-dom` version: 3.2.4
- `node` version: 14.16.1
- `npm` version: 6.14.12

Relevant code or config

```javascript
      expect(onChange.mock.calls[0][0].checked).toBe(true);
```

What you did:
    Wanna check '.checked' value from the argument
    
What happened:
     I got this from eslint plugin:
       ` ESLint: Use toBeChecked() instead of checking .checked directly(jest-dom/prefer-checked)`
     But if I use it, I'll get this error from the test:
        `received value must be an HTMLElement or an SVGElement.`

Problem description:

 Actually, if I create an object like this, and try to check 'checked' value, I'll get same error:
```javascript
      const obj = {
          checked: true,
      }; 
      //ESLint: Use toBeChecked() instead of checking .checked directly(jest-dom/prefer-checked)
      expect(obj.checked).toBe('true');
```

Suggested solution:
   I think need to fix it :)

**Comment by G-Rath** [comment]
That's something of a limitation of ESLint that we can't really improve on (aside from using type-checking, which we could do but wouldn't solve this for everyone since not everyone uses TypeScript).

Because we can't know anything about the type, we have to assume that with the way you're using the `checked` property that you're working with a DOM element. 

Technically we could ease that restriction to support any object with a `checked` property, but then the rule isn't just for DOM elements - I'm not against exploring that, but it would be contrary to what these matchers are expected to be used for.

**Comment by benmonro** [comment]
I'd recommend using lint disable for edge cases like this.
