### ISSUE TITLE
feature: prefer toBeEmpty

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-jest-dom#7]
report on `expect(element.firstChild).toBeNull()` and potentially autofix to `expect(element.firstChild).toBeEmpty()`

@gnapse thoughts on this one?

**Comment by gnapse** [comment]
Could be. Though technically the implementation of `toBeEmpty` is about detecting if `element.innerHTML === ''`. Other cases that come to mind that could be better described with `toBeEmpty`:

```js
expect(element.innerHTML === '').toBe(true)
expect(element.innerHTML).toEqual('')
```

Also, I think what you meant above is that the original `expect` should be converted to `expect(element).toBeEmpty()`, right? Because right now it says `expect(element.firstChild).toBeEmpty()`.

**Comment by benmonro** [comment]
Yes that's what I meant. I'm converting enzyme tests to RTL and that's what they were doing

**Comment by gnapse** [comment]
Ok. In anycase, yes, a rule like this makes sense.
